resource:
  urls:
    tradingView: https://bellawebapp-chandan867s-projects.vercel.app/charts
    news: https://bella.thumbnailai.online/cryptoNews/trendingNews
    detailedReport: https://bellawebapp-chandan867s-projects.vercel.app/detailedReport
commands:
  start:
    message: |
      <b>CryptoTradeGPT - Your crypto info & insights hub!</b>

      Get the latest info & analysis with cutting-edge AI & real-time data. I can answer your questions about the crypto market and specific currencies. 

      Here's what I can do 👇

      👉 Get the latest info and analytics about any Crypto currency.
      👉 Ask me anything about buying pressure, liquidity, trends, and more!
      👉 I can answer about risky bets, blue chips, top gainers/losers

      Use /hot_questions to see what crypto questions I can answer.

    select_option: "Click on this option to begin"
  hot_questions:
    message: "Here are a few examples:"
    template_questions: |
      ⭐ 1. Which cryptocurrencies are showing the most <b><i>rising liquidity</i></b> right now?
      ⭐ 2. Are there any coins with significant <b><i>buying pressure</i></b> that I should be watching?
      ⭐ 3. What are some <b><i>blue chips</i></b> that have shown <b><i>solid performance</i></b> recently?
      ⭐ 4. Are there any <b><i>risky bets</i></b> in the market with potential for high gains?
      ⭐ 5. What are the top <b><i>trending</i></b> cryptocurrencies right now?
  trade:
    message: "🎯 Ready to trade and conquer the crypto market? 🎯\nHead over to our cutting-edge webapp and unleash your trading potential! 📊💸\nExperience seamless trading like never before with CryptoTradeGPT! 🌐🔒"
  portfolio:
    message: "📜 Your Portfolio at Your Fingertips! 📜\nWith CryptoTradeGPT, you can easily track and manage your cryptocurrency portfolio! 💼📊\nStay on top of your investments and make informed decisions! 📈🎯"
  earn:
    message: "💡 Want to earn while learning about cryptocurrencies? 💡\nCryptoTradeGPT offers incredible opportunities to boost your crypto earnings! 💪🌱\nStay tuned for exclusive promotions, giveaways, and rewards! 🎉🎁"
  help:
    message: "🙋‍♂️ Need assistance? Our friendly help team is here for you! 🙋‍♀️\nWhether you have questions, concerns, or feedback, we're just a message away! 📩💬\nYour satisfaction is our top priority! 😊👍"
  webapp:
    prompt: "Let's do this..."
    data_response: "Your data was:"
